### ISSUE TITLE
也是醉了

### ISSUE THREAD

**Issue by ckeyer** [sllt/test#1]
ܝܘܚܢܢ ܒܝܬ ܐܦܪܝܡ 

سمَـَّوُوُحخ ̴̐خ ̴̐خ ̴̐خ امارتيخ ̴̐خ 

Power

لُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ

冗

**Comment by sllt** [comment]
醉你妹

**Comment by ckeyer** [comment]
,,,,,,,
